name: ESLint and Jest

on:
  pull_request:
    branches:
      - main

jobs:
  eslint-jest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
        continue-on-error: true

      - name: Run Jest
        run: npm test
        continue-on-error: true

      - name: Check for ESLint and Jest errors
        run: |
          eslint_exit_code=$?
          jest_exit_code=$?

          if [ $eslint_exit_code -ne 0 ] || [ $jest_exit_code -ne 0 ]; then
            echo "ESLint or Jest found errors. Blocking the pull request."
            exit 1
          fi
