name: ESLint, Jest, and Commit Linter

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  eslint-jest-commitlint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Copy repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm ci || exit 1

      - name: Run ESLint
        run: npm run lint

      - name: Run Jest
        run: npm test

      - name: Check for ESLint and Jest errors
        run: |
          eslint_exit_code=$?
          jest_exit_code=$?

          if [ $eslint_exit_code -ne 0 ] || [ $jest_exit_code -ne 0 ]; then
            echo "ESLint or Jest found errors. Blocking the pull request."
            exit 1
          fi

      - name: Install commitlint
        run: npm install --global @commitlint/cli @commitlint/config-conventional

      - name: Lint commits
        run: |
          git fetch origin pull/${{ github.event.pull_request.number }}/merge
          git checkout FETCH_HEAD
          npx commitlint --from=$GITHUB_SHA

      - name: Check commit linting errors
        run: |
          commitlint_exit_code=$?

          if [ $commitlint_exit_code -ne 0 ]; then
            echo "Commit linter found errors. Blocking the pull request."
            exit 1
          fi
